# used by VSCode REST Client Plugin
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### Get all users
get http://localhost:3000/users

### Get users by age
get http://localhost:3000/users?age=25

### Get a user by ID
get http://localhost:3000/users/4

### Create a new user
post http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe"
}

### Create a new user with invalid name
post http://localhost:3000/users
Content-Type: application/json

{
  "name": 4
}

### Update a user
put http://localhost:3000/users/4
Content-Type: application/json

{
  "name": "Jane Doe",
  "age": 25,
  "admin": true
}

### Update a user without admin rights
put http://localhost:3000/users/4
Content-Type: application/json

{
  "name": "Jane Doe",
  "age": 25
}

### Delete a user
delete http://localhost:3000/users/4
